# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efd0764f6adbfab0cdf549ca8ad0fb115acdd62a8967c4669775e937847c8c9b46ac61c2db2e7856521c0918da03e07e62f29d9a186def0caa06285a00a62bd3

test:
  secret_key_base: e0767984fbbeb5dcba8a91809a2d1a34a2d130951b9603bcc54231a0a8548e2cd3238d17a015a93f927a5af474a935836abca6771673f90e3cd6fda057de5ed1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
